### ISSUE TITLE
Selected character always reverts to first character on area change

### ISSUE THREAD

**Issue by Punishbear** [Razzmatazzz/RemnantSaveManager#10] opened 2020-05-15 16:08 UTC
* log into hardcore character, which is my second one
* set SaveManager Character to that one
* change zone
* SaveManager selected character is back to first one

Happens every time. It's annoying.

**Comment by Razzmatazzz** [comment] 2020-05-15 17:11
I can't reproduce this behavior. I played with my hardcore character, which is third out of three for me, and that character stayed selected in the analzyer as it updated. What version of the program are you running?

**Comment by Punishbear** [comment] 2020-05-16 10:01
Strange. The newest version. I started using this app at 1.95.17 I think. And as far as I know, this has happened in every version since then.

**Comment by Punishbear** [comment] 2020-05-16 10:37
I've created a potential fix for it myself. I don't know why it works for you, but my guess is a timing issue. Because the save is modified 4 times, and I have the game installed on a M.2 SSD, I guess the order in which the app handles the reload of data is borked. 🤔 

But I can't push a branch with my fix, of course.

**Comment by Razzmatazzz** [comment] 2020-05-16 11:25
My game is also running on an M.2 SSD. The game saving 4 times shouldn't really matter as none of those saves change the number of characters, which is the only thing that should cause the character selection to change. If your fix involves moving the updateCurrentWorldAnalzyer to the OnSaveTimerElapsed event handler, I considered doing it that way but decided not to because it would make people have to wait for the analyzer to refresh. When rolling lots of adventure modes in on a row looking for a particular event, adding 10 seconds to each would get very annoying. I suppose I could add a counter and only update the analyzer once it reaches 4.

**Comment by Punishbear** [comment] 2020-05-16 17:03
What I noticed while debugging was that the selectedIndex changes multiple times from 0 to -1, which ultimately causes your if statements at line 125 and 126 to set it to 0. That's where my guess is coming from.

My fix saves the SelectedIndex in a Property (in CmbCharacter_SelectionChanged) and gets it in LoadData, thus always just setting the last SelectedIndex on save change.

**Comment by Razzmatazzz** [comment] 2020-05-16 18:10
I still haven't been able to replicate the issue. But I think it'll be fixed in the next version. I just added the following line the the start of the CmbCharacter_SelectionChanged event handler:
`if (cmbCharacter.SelectedIndex == -1 && listCharacters.Count > 0) return;`
That should cause it to ignore any cases where the selection is changed to -1.

**Comment by Punishbear** [comment] 2020-05-16 18:40
ok thanks

**Closed** 2020-05-16 18:47 UTC
